### ISSUE TITLE
bug: Lockscreen info not displayed anymore

### ISSUE THREAD

**Issue by dylancom** [tanhakabir/SwiftAudioPlayer#106]
Since I recently upgraded to the latest pod of this project, the lock screen doesn't show info anymore (artist, title & artwork).
I also tested the Example project to make sure it's not related to my code and also there I don't see any lock screen info.

I found that self.mediaInfo is nil at: https://github.com/tanhakabir/SwiftAudioPlayer/blob/master/Source/SAPlayerPresenter.swift#L123

**Comment by tanhakabir** [comment]
Will look into today!

**Comment by dylancom** [comment]
@tanhakabir I found that I was using 3.0.0 before and if I switch back to 3.0.0 the lockscreen is working fine again.

**Comment by tanhakabir** [comment]
Thanks for testing that for me! I'm having a couple issues with my Apple Dev account right now so I can't test on device but just to confirm you are sending lockscreen info on start correct? I see that the latest example app wasn't

**Comment by tanhakabir** [comment]
pushed a fix to the example app to pass in the lockscreen info

**Comment by dylancom** [comment]
@tanhakabir no thanks, I was hoping I could push a PR myself but haven't found the fix yet. Yes I'm using  SAPlayer.shared.startSavedAudio(withSavedUrl: url, mediaInfo: info) from the start. 
What I found is that handleLockscreenInfo(info) get's called with the correct info, but inside attachForUpdates self.mediaInfo seems to remain nil.

**Comment by tanhakabir** [comment]
Hmm I'm not reproing that at the moment but once I can fix my dev account I can check on my device to confirm

**Comment by dezinezync** [comment]
I am also able to reliably reproduce @dylancom's issue against the master branch.

**Comment by dezinezync** [comment]
I've traced it down to `func handlePlayStreamedAudio(withRemoteUrl url: URL, bitrate: SAPlayerBitrate)` inside `SAPlayerPresenter` line 94. 

It calls `handleClear()` which removes the media info from the presenter.

**Comment by dylancom** [comment]
@dezinezync good catch. So it seems to be introduced by this commit: https://github.com/tanhakabir/SwiftAudioPlayer/commit/542f65f044a3d637fc10486aeb9cb19b5a9d71c6
(The start of adding queuing functionality)
