### ISSUE TITLE
crash when seek online streaming song or play a finished playing song again

### ISSUE THREAD

**Issue by cendolinside123** [tanhakabir/SwiftAudioPlayer#11]
crash when seek online streaming song or play a finished playing song again on `let diff = lastOffsetPolled - oldValue` inside didSet `var lastOffsetPolled: UInt64 = 0` on AudioThrottle.swift
tested on:
ios: 10.3,13.1.2
iphone: iphone 5,iphone 6

**Comment by tanhakabir** [comment]
I believe this should be resolved in version 1.1.1.
