### ISSUE TITLE
Hi, Do you plan to add loop mode?

### ISSUE THREAD

**Issue by zangqilong198812** [tanhakabir/SwiftAudioPlayer#123]
Play the audio file loop. and It is useful.

**Comment by tanhakabir** [comment]
It's possible right now through editing the queue but I've received a couple requests for this so I'll look into making a solution within the library

**Comment by Husseinhj** [comment]
The issue #124 is about play loops

**Comment by tanhakabir** [comment]
Hey! Added looping in the library accessible through `SAPlayer.Features.Loop.enable()` and `SAPlayer.Features.Loop.disable()`: https://github.com/tanhakabir/SwiftAudioPlayer/blob/98dc7cfa3cbf8102d7f191d17ad85e89fbd37af6/Source/SAPlayerFeatures.swift#L135-L156
