### ISSUE TITLE
Crash from queuing short audio on loop

### ISSUE THREAD

**Issue by tanhakabir** [tanhakabir/SwiftAudioPlayer#128]
Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: nil == owningEngine || GetEngine() == owningEngine'

**Comment by iosDeveloperAuthenticode** [comment]
Please explain this issue i got the same issue when i pop from the streaming screen i called saplayer.shared.stopstreamingaudio() but when i came with the same audio url it got crashed by giving the same details as shown above
