### ISSUE TITLE
AudioQueue is always empty

### ISSUE THREAD

**Issue by AndreyPoznyak** [tanhakabir/SwiftAudioPlayer#152]
`public var audioQueued: [SAAudioQueueItem]` - this one appears to be empty since it is not proxy-ed from `presenter` - in `presenter` it is up to date

**Comment by twjazzhuang** [comment]
SAPlayer.swift  
185:
it should get presenter.audioQueue

    public var audioQueued: [SAAudioQueueItem] {
        get {
            return presenter.audioQueue
        }
        set {
          presenter.audioQueue = newValue
        }
    }

@tanhakabir  can u help it?
thanks

**Comment by tanhakabir** [comment]
Yep! Externally you should be working with the audio queue saved in the `presenter`. Is there an issue with it?

**Comment by AndreyPoznyak** [comment]
@tanhakabir of course, `presenter` is not public. In order to get access to the queue the code should be adjusted as @twjazzhuang suggested

**Comment by tanhakabir** [comment]
Fixed and published from https://github.com/tanhakabir/SwiftAudioPlayer/pull/149
