### ISSUE TITLE
create a SwiftPackage

### ISSUE THREAD

**Issue by tanhakabir** [tanhakabir/SwiftAudioPlayer#34]

**Comment by beks92** [comment]
Hi, receiving an error from the Swift Package Manager when trying to add this dependency. The error is: 

"https://github.com/tanhakabir/SwiftAudioPlayer.git has no Package.swift manifest for version 2.11.0"

Is this thread that you opened in relation to that as well? Any suggestions on what I should do? Thank you!

**Comment by tanhakabir** [comment]
Yes, for right now SwiftAudioPlayer is only available through Cocoapods. I'll be adding SPM support soon but not available at the moment.

**Comment by EricWVGG** [comment]
users on ARM Macs attempting to install via Cocoapods, here's some tips on getting around cocoapods: https://stackoverflow.com/questions/64901180/running-cocoapods-on-apple-silicon-m1
