### ISSUE TITLE
Issue downloading audio

### ISSUE THREAD

**Issue by tanhakabir** [tanhakabir/SwiftAudioPlayer#35]
It seems to work on simulator but not on device. Callbacks with progress and completion handler never reach.

**Comment by AmilaDiman** [comment]
Any update on this issue? Im having this exact issue

**Comment by nshapkar** [comment]
Im having the same issue

**Comment by jw1540** [comment]
@nshapkar @AmilaDiman it looks like it's an issue with the isDiscretionary bool set on the URLSession. removing this "fixes" the issue for me. It's likely that the system is dealing with large file transfers and looking for an optimal time to begin the transfer.
