### ISSUE TITLE
required condition is false: nil == owningEngine || GetEngine() == owningEngine

### ISSUE THREAD

**Issue by ucelme** [tanhakabir/SwiftAudioPlayer#36]
Hello. I use  MPMediaPickerController to play files. It works fine with first file, but if I add the second file I get crash with error:

`required condition is false: nil == owningEngine || GetEngine() == owningEngine
`

This is my code for MPMediaPickerController:
```
func mediaPicker(_ mediaPicker: MPMediaPickerController, didPickMediaItems mediaItemCollection: MPMediaItemCollection) {

        dismiss(animated: true, completion: nil)
        let item: MPMediaItem = mediaItemCollection.items[0]
        let pathURL = item.value(forProperty: MPMediaItemPropertyAssetURL) as? URL
        SAPlayer.shared.startSavedAudio(withSavedUrl: pathURL!)
        SAPlayer.shared.play()
    }

```

**Comment by dylancom** [comment]
I'm having the same error.

**Comment by drynose** [comment]
Hi!
I have the same issue. During steaming audio, try to Strat streaming next track, after Playing status become .ended.
For me this become as bad hot fix:
```
DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + .seconds(1)) {
    //play next
}
```

Any actions with SAPlayer did not lead to fix. Including SAPlayer.shared.clear() does not help in this case.
In debug, it seems to be trouble with threads, queue.async.

**Comment by fashionprivate** [comment]
@drynose I'm experiencing the same your problem :-(
The only solution is to play the next track within the DispatchQueue.main.asyncAfter block.

**Comment by fmp6475** [comment]
Same issue here using startRemotePlay. DispatchQueue.main.asyncAfter 1 second can reduce the chance of crash but it still happen randomly.

**Comment by jiangdi0924** [comment]
😐 Has anyone found a good solution ？

**Comment by tanhakabir** [comment]
Hey everyone! I recommend calling clear before starting another stream as well as using the audio queue if you're planning to play one audio after another. I'm going to close this issue for now unless there's still a similar scenario that causes this crash
