### ISSUE TITLE
PlayerStatus callback suddenly return false value cause by the buffer is "Not enough data for read-conversion operation" 

### ISSUE THREAD

**Issue by cendolinside123** [tanhakabir/SwiftAudioPlayer#4]
so it's happend when I try playing streaming from this url "https://cdn.fastlearner.media/bensound-rumble.mp3" using project from example folder. 
The SAPlayer.Updates.PlayingStatus.subscribe sometime return false and player stopping playing the song. 
after I try to debuging process inside `converter.pullBuffer(withSize: PCM_BUFFER_SIZE)` the error cause on the buffer is "Not enough data for read-conversion operation"  with no OSStatus error ReaderNotEnoughDataError (932332582)
Almost all streaming with duration below 1 hour got this error

this happen on
ios: 10.3 , 13.1.2 (rarely happend in this os version)
iphone: iphone 5, iphone 6s (rarely happened)

**Comment by cendolinside123** [comment]
I test it again on version 1.1.0 with:
ios: 10.3
iphone: iphone 5
xcode: 11.1
The SAPlayer.Updates.PlayingStatus.subscribe sometime still return false and player stopping playing the song, still get error message "Not enough data for read-conversion operation"

**Comment by tanhakabir** [comment]
Is it happening on its own or are you seeking/scrubbing through the audio beforehand?

**Comment by cendolinside123** [comment]
> Is it happening on its own or are you seeking/scrubbing through the audio beforehand?

I test it without seeking/scrubbing through the audio beforehand

**Comment by tanhakabir** [comment]
Hm I can't seem to repro this bug. To clarify, you're

1. streaming the Soundbite
2. letting it play on
3. it gets stuck on its own and the "Not enough data for read-conversion operation" with no OSStatus error ReaderNotEnoughDataError (932332582)" comes up?

**Comment by cendolinside123** [comment]
yes, I'm streaming the Soundbite and letting it play on. I got stuck on its own, if i debug it, I found error log "Not enough data for read-conversion operation". it can be reproduce if the network condition is not stable too
to reproduce like from this video
http://www.mediafire.com/file/mp70ybkyrh4fjld/VID20191127171102.mp4/file
this's will happend when seek music player on stuck by error condition
https://www.mediafire.com/file/jt8skx345uev1g9/VID20191127171130.mp4/file

this is how to set bad connection
![IMG20191128004046](https://user-images.githubusercontent.com/29350026/69747488-0cb31780-1179-11ea-971f-4e97528d657f.jpg)
