### ISSUE TITLE
Radio stream support

### ISSUE THREAD

**Issue by dylancom** [tanhakabir/SwiftAudioPlayer#42]
When I play a radio stream with startRemoteAudio, it's really buggy.
A lot of times it will pause shortly after, or increase the playback rate automatically, or not even play at all.
Does the player expect a stream with a known length or something?

**Comment by tanhakabir** [comment]
Started work on this

**Comment by kmenager** [comment]
Hi @tanhakabir,
I experience the same issue as @dylancom 
I see a branch issue-42 (merged) but I still have an issue with infinite stream audio. 
Do you have any update on this feature?

**Comment by EricWVGG** [comment]
I'm attempting to use this with PLS streams like `https://somafm.com/groovesalad256.pls`. Not getting any playback at all.

**Comment by tanhakabir** [comment]
Hmm at this moment I'm not handling "infinite" streams well but I can see this weekend! Sorry about the delay!

**Comment by EricWVGG** [comment]
wish I could help with a PR, unfortunately this is all a bit advanced for me!

**Comment by tanhakabir** [comment]
@EricWVGG no worries! I'll have a crack at it this weekend

**Comment by tanhakabir** [comment]
@EricWVGG are you using the latest version of the library? I can't seem to repro this on my end with the sample app on the simulator. Here's a gif of me using the same radio link and it working fine:
![recording (25)](https://user-images.githubusercontent.com/12758612/113809487-13fb1580-971d-11eb-8cc2-b7b8d7185e17.gif)

**Comment by tanhakabir** [comment]
I think if there's a rate issue it's due to the server from the radio not passing back enough data to the app to actually have a faster playback. But all other manipulations should work fine. I played the radio for awhile at 1x and it was fine for me, not choppy or laggy

**Comment by EricWVGG** [comment]
Dang. I'm still encountering the same issue. Definitely the latest version of your library (I just tried again with a fresh pull).

I can usually get it to play for about 45 seconds before it starts skipping and ultimately halts, even played at 75% speed. (I have no intention to do any manipulations at all, I'm just trying to use this to get playback and an audio tap for visualizations.)

I hate to be a bother, but could you tell me if you can keep that audio stream playing for like two minutes?

**Comment by tanhakabir** [comment]
Hey! Will try! Sorry didn't see this notification!

**Comment by EricWVGG** [comment]
:) are you still in Seattle? Pick a wine store and I'll get a couple nice bottles put behind the counter for you

**Comment by tanhakabir** [comment]
@EricWVGG almost have a fix, hoping to finish tomorrow morning!

**Comment by tanhakabir** [comment]
> :) are you still in Seattle? Pick a wine store and I'll get a couple nice bottles put behind the counter for you

Hahah you're too nice! Don't worry about it! I appreciate the thought!

**Comment by tanhakabir** [comment]
@EricWVGG  and everyone else on this thread. I've added an option to set the bitrate to low for radio streams which should make it much smoother now. I tested on the example app like this: https://github.com/tanhakabir/SwiftAudioPlayer/blob/b270cf86abd48bc5949afe1977e8d107f6554abd/Example/SwiftAudioPlayer/ViewController.swift#L315

**Comment by EricWVGG** [comment]
I'll check it out this afternoon!

**Comment by EricWVGG** [comment]
_This works._ Thank you so much, Tanha.
