### ISSUE TITLE
Library Stopped working after upgrading to Xcode 12

### ISSUE THREAD

**Issue by bahaahany-eg** [tanhakabir/SwiftAudioPlayer#45]
Please can you advise on this issue after upgrading to xcode 12 IOS 14
here is the error log & the code that has the problem in AudioParser.swift

```
 init(withRemoteUrl url: AudioURL, parsedFileAudioFormatCallback: @escaping(AVAudioFormat) -> ()) throws {
        self.url = url
        self.parsedFileAudioFormatCallback = parsedFileAudioFormatCallback
        self.throttler = AudioThrottler(withRemoteUrl: url, withDelegate: self)
        
        let context = unsafeBitCast(self, to: UnsafeMutableRawPointer.self)
        //Open the stream and when we call parse data is fed into this stream
        guard AudioFileStreamOpen(context, ParserPropertyListener, **ParserPacketListener**, kAudioFileMP3Type, &streamID) == noErr else {
            throw ParserError.couldNotOpenStream
        }
    }
```

Cannot convert value of type '(UnsafeMutableRawPointer, UInt32, UInt32, UnsafeRawPointer, UnsafeMutablePointer<AudioStreamPacketDescription>) -> ()' to expected argument type 'AudioFileStream_PacketsProc' (aka '@convention(c) (UnsafeMutableRawPointer, UInt32, UInt32, UnsafeRawPointer, Optional<UnsafeMutablePointer<AudioStreamPacketDescription>>) -> ()')

**Comment by jvillegasmx** [comment]
I have the same issue, i just update it,  and it is sending the same error, help need it

**Comment by moyinzunza** [comment]
Don't worry I'm here 

In **AudioParserPacketListener.swift**

in line 35 

`func ParserPacketListener (_ context: UnsafeMutableRawPointer, _ byteCount: UInt32, _ packetCount: UInt32, _ streamData: UnsafeRawPointer, _ packetDescriptions: UnsafeMutablePointer<AudioStreamPacketDescription>?) {`

Add the simbol for optional value then in line 55 
unwrap the packetDescriptions

`let audioPacketDescription = packetDescriptions![i]`

And it's all
Enjoy it

**Comment by bahaahany-eg** [comment]
> Don't worry I'm here
> 
> In **AudioParserPacketListener.swift**
> 
> in line 35
> 
> `func ParserPacketListener (_ context: UnsafeMutableRawPointer, _ byteCount: UInt32, _ packetCount: UInt32, _ streamData: UnsafeRawPointer, _ packetDescriptions: UnsafeMutablePointer<AudioStreamPacketDescription>?) {`
> 
> Add the simbol for optional value then in line 55
> unwrap the packetDescriptions
> 
> `let audioPacketDescription = packetDescriptions![i]`
> 
> And it's all
> Enjoy it

Thanks moyinzunza it works

**Comment by tanhakabir** [comment]
@bahaahany-eg thank you! I can make the change but would you like to and make a PR for it since it was your fix?

**Comment by moyinzunza** [comment]
> @moyinzunza thank you! I can make the change but would you like to and make a PR for it since it was your fix?

Sure, I already sent PR 👍
