### ISSUE TITLE
Pitch doesn't work because of kAudioUnitSubType_AUiPodTimeOther algorithm of the default AVAudioUnitTimePitch

### ISSUE THREAD

**Issue by nt4f04uNd** [tanhakabir/SwiftAudioPlayer#50]
You should document this and allow to change this, because now I have to apply two modifiers insted of one, or rather to fork your repo and change this in my fork

See https://developer.apple.com/forums/thread/6050

https://github.com/tanhakabir/SwiftAudioPlayer/blob/dd54d81573f079945b8c46191c5b75f176fe4467/Source/SAPlayer.swift#L172-L181

**Comment by tanhakabir** [comment]
Added function, `clearAudioModifiers()` to be called at beginning  to remove pitch modifier and documentation for this. In general you can just remove all the modifiers in `audioModifiers` before calling `startSavedAudio()` or `startRemoteAudio()`. You shouldn't need to combat the default modifier by adding 2 modifiers or needing to fork and change; you be able to just remove the pitch modifier from the list.
