### ISSUE TITLE
`Reached the end of the file` error at the random places of file while playing with startRemoteAudio

### ISSUE THREAD

**Issue by nt4f04uNd** [tanhakabir/SwiftAudioPlayer#53]
I get this exception at about 20 seconds pass the start of the file, while the file itself has a duration like 140 seconds and more
`AudioConverterErrors.swift:errorDescription:78:: Reached the end of the file`

Doesn't actually make the playback any worse though (except, after the seek function I have to also call play if the audio has been playing, but that's not a big deal).

**Comment by tanhakabir** [comment]
No longer reproing. But feel free to reopen if you see this error still
