### ISSUE TITLE
Bug: play / pause work incorrect by seeking streamed audio, resulting in blank playback

### ISSUE THREAD

**Issue by peterpaulis** [tanhakabir/SwiftAudioPlayer#55]
When the audio seeking on the lock screen is used and the track is changed to different positions, than blank empty audio is played and the play/pause button cannot be triggered to pause and is always playing

moreover when enabling debug, i always get a bunch of

`[DEBUG] AudioConverterErrors.swift:errorDescription:72:: Not enough data for read-conversion operation`

no matter the source or the stream

**Comment by peterpaulis** [comment]
i think its a bug when seekTo is used, the audio is paused, but the corresponding state is not updated

for the above, this quic fixed it (adding `presenter.handlePlay()`)

```
        commandCenter.changePlaybackPositionCommand.addTarget { [weak presenter] event in
            guard let presenter = presenter else {
                return .commandFailed
            }
            if let positionEvent = event as? MPChangePlaybackPositionCommandEvent {
                presenter.handleSeek(toNeedle: Needle(positionEvent.positionTime))
                presenter.handlePlay()
                return .success
            }
            
            return .commandFailed
        }
```

note that also after seeking i have to also do play

```
        SAPlayer.shared.seekTo(seconds: Double(sender.value))
        SAPlayer.shared.play()
```

**Comment by peterpaulis** [comment]
so it boils down to play / pause working incorrect when seeking

This is also the reason for the lock screen player to fails... as the audio is stopped, but the player keeps on playing blank audio

**Comment by peterpaulis** [comment]
moreover there seems to be a race condition inside 
seekHelperDispatchQueue(needle: Needle) when playerNode.stop() is called

the seekHelperDispatchQueue of the AudioStreamEngine looks flawed

<img width="447" alt="Screenshot 2020-12-02 at 09 45 15" src="https://user-images.githubusercontent.com/1956972/100849604-16a1e180-3483-11eb-8091-dee16d87c8ec.png">

**Comment by peterpaulis** [comment]
the deadlock on 

`playerNode.stop()`

seems to be fixed by using

`playerNode.pause()`

but still the lockscreen player runs into issues while seeking

**Comment by peterpaulis** [comment]
i tried to battle this and modify the executions to prevent playerNode.stop() from causing a deadlock, but didnt found a solution

**Comment by peterpaulis** [comment]
the thread issue may lie here, as the completion block of scheduleBuffer is executed on a different thread than anything else

```
self?.playerNode.scheduleBuffer(nextScheduledBuffer) {
                    self?.numberOfBuffersScheduledInTotal -= 1
                    self?.pollForNextBufferRecursionHelper()
                }
```

**Comment by peterpaulis** [comment]
Fixed the thread issue here
https://github.com/tanhakabir/SwiftAudioPlayer/pull/56

other issues are still open :(

**Comment by peterpaulis** [comment]
Ok, i am giving up on this project... the streaming is broken beyond repair, switching to https://github.com/tumtumtum/StreamingKit

**Comment by tanhakabir** [comment]
Fixed in https://github.com/tanhakabir/SwiftAudioPlayer/pull/132
