### ISSUE TITLE
investigate removing singleton pattern

### ISSUE THREAD

**Issue by tanhakabir** [tanhakabir/SwiftAudioPlayer#66]

**Comment by jw1540** [comment]
👍 great suggestion, would be interested in helping out if possible :)

**Comment by tanhakabir** [comment]
Hey @jw1540! I'm curious to know why removing the singleton pattern would be helpful for you? Do you need more than one player at a time?

**Comment by jw1540** [comment]
Right now, no. I pretty much share the instance across a "small" player and a large one. My question was primarily: what's the reasoning behind adopting the singleton pattern, and what does it offer besides an easily accessible global instance? It might be the case that a singleton makes sense and leaving it in is ok. I'm just curious as to whether it could be removed.

**Comment by tanhakabir** [comment]
closing because only one AVAudioEngine can be running at one time and so having 2 AVAudioEngines wouldn't be necessary
