### ISSUE TITLE
[Feature Request] Add in ability to pause after a delay, "skip" silences.

### ISSUE THREAD

**Issue by jw1540** [tanhakabir/SwiftAudioPlayer#70]
Hey, 

Recently forked the project because I needed a couple of custom methods on the player but wanted to offer them as suggestions: 

1. Ability to pause after a delay (useful for sleep timers). 
2. Skipping silences. 

For 1 I have an implementation on a fork and would be happy to raise a PR. For the second feature request I have a very rough implementation which I can share, though I'm not sure it's the best possible solution. Let me know if this is something you'd think would be valuable and I'll raise a PR! 

Cheers, 
Joe

**Comment by tanhakabir** [comment]
Hey! Yeah it would be awesome if you could PR both! For the second we can look at it together :)

**Comment by jw1540** [comment]
Hey @tanhakabir I can't seem to raise a PR, do I need contributing access for this?

**Comment by tanhakabir** [comment]
Hey! So you can fork my repo and then create a PR from your fork

**Comment by jw1540** [comment]
Thanks, raised - let me know what you think.
