### ISSUE TITLE
Add documentation for skip silences feature

### ISSUE THREAD

**Issue by tanhakabir** [tanhakabir/SwiftAudioPlayer#81]
Added Skip Silences feature but we have no documentation for the metering logic that it uses. 

@jw1540 would you be able to link to me the resources you used or document the scaling function and the tap callback?

**Comment by jw1540** [comment]
hey @tanhakabir - apologies, I primarily used the info in this 
https://www.raywenderlich.com/5154-avaudioengine-tutorial-for-ios-getting-started#toc-anchor-005

**Comment by tanhakabir** [comment]
All good! It just makes it easier having links to what's happening :)
