### ISSUE TITLE
Icy metadata and custom headers

### ISSUE THREAD

**Issue by nosenergies** [tanhakabir/SwiftAudioPlayer#85]
Hi,
I just discovered your library and I was wondering if it implements icy-metadata (timedMetadata in AVPlayer) and also custom headers (like using a custom user-agent).
Thanks!

**Comment by tanhakabir** [comment]
Hey! It doesn't right now, but I can look into that

**Comment by nosenergies** [comment]
I wanted to start helping by checking your code and maybe make a PR. I followed the steps: clone the repo, cd, pod install and this does not work. I get this message: "[!] No `Podfile' found in the project directory.". Then I tried to open the project in Xcode and here is what I get when I open the [folder:]
![Capture d’écran 2021-03-22 à 09 21 57](https://user-images.githubusercontent.com/33221941/111960515-27d53380-8af0-11eb-8bac-f9c6a36783a1.png)
Thanks

**Comment by nosenergies** [comment]
I also found that wich might help: https://github.com/dimitris-c/AudioStreaming/blob/main/AudioStreaming/Streaming/AudioPlayer/Processors/IcycastHeadersProcessor.swift.

**Comment by dimitris-c** [comment]
@nosenergies Since I happened to see this issue, the link you mentioned is for the http headers that some servers send as part of the stream. The extraction of metadata from the stream happens here https://github.com/dimitris-c/AudioStreaming/blob/main/AudioStreaming/Streaming/AudioPlayer/Processors/MetadataStreamProcessor.swift

**Comment by tanhakabir** [comment]
@nosenergies when you cd'd did you cd into `Example` folder for the example app? Or if you're using it in your own project, you need to add the pod to your Podfile and then run `pod install`. I'll update the README to clarify this.

I'll look at @dimitris-c's repo later today

**Comment by nosenergies** [comment]
@tanhakabir Any update on this feature? Thanks

**Comment by tanhakabir** [comment]
Hey @nosenergies, with the help from @cntrump we added HTTP Header fields. As for the Icy metadata, I'm going to create a separate issue for that but it looks like a bigger change so I probably won't have time to get to it soon.

New issue: https://github.com/tanhakabir/SwiftAudioPlayer/issues/129
