### ISSUE TITLE
Playback stops (playing status == .buffering) after 55 seconds when streaming

### ISSUE THREAD

**Issue by niczyja** [tanhakabir/SwiftAudioPlayer#90]
Hi @tanhakabir 👋 Fisrt of all let me say that I'm impressed by the amount of work you've put into creating this player 🙇‍♂️

I'm experiencing an issue when streaming an audio file. Player is playing up until 55th second and then it stops. It happens in the example app and in my app consistently.

When I turned debug logging I can see that at this point AudioStreamEngine runs out of buffers and status is changed to buffering. When I skip over this point during playback (before it comes to this time) everything works fine, so the data is there is't just not passed over to the engine. Here's the log from this moment:

`2021-04-15 11:13:49.219419+0200 Euphoric[4607:1766321] [DEBUG 🐝🐝🐝🐝] AudioStreamEngine.swift:updateNetworkBufferRange():210:: [Optional("loaded (0.0, 4002.089795918367), numberOfBuffersScheduledInTotal: 1, isPlayable: true")]`
`2021-04-15 11:13:49.316270+0200 Euphoric[4607:1766321] [DEBUG 🐝🐝🐝🐝] AudioStreamEngine.swift:numberOfBuffersScheduledInTotal:74:: [Optional("number of buffers scheduled in total: 0")]`
`2021-04-15 11:13:49.407243+0200 Euphoric[4607:1766321] [INFO  🖤🖤🖤🖤] AudioStreamEngine.swift:isPlayable:126:: isPlayable status changed: false`
`2021-04-15 11:13:49.407730+0200 Euphoric[4607:1766321] [DEBUG 🐝🐝🐝🐝] AudioStreamEngine.swift:updateNetworkBufferRange():210:: [Optional("loaded (0.0, 4002.089795918367), numberOfBuffersScheduledInTotal: 0, isPlayable: false")]`

I'd like to fix the issue myself, but I don't have good understanding of the code yet, so I was hoping that maybe you as an author have rough idea where this issue may come from and where should I start looking in the code.

Best,
Maciej.

**Comment by tanhakabir** [comment]
Hey! @niczyja! yes definitely I can look into this! super weird edge case that I haven't run into yet but excited to solve! What's the url of the file you're streaming?

**Comment by niczyja** [comment]
@tanhakabir thank you. In the Example app it happens with poscast stream from url: https://chtbl.com/track/18338/traffic.libsyn.com/secure/acquired/acquired_-_armrev_2.mp3?dest-id=376122 and in my app it happens for every podcast url that I've tried so far.
