### ISSUE TITLE
audioPackets and throttler in AudioParser crash frequently when running on device

### ISSUE THREAD

**Issue by fayinsky** [tanhakabir/SwiftAudioPlayer#94]
Identified two issues in AudioParser when using SAPlayer for streaming on my test device.

1. audioPackets is not multithread friendly which made SAPlayer impossible to use on my test device. This can be solved by using a seperate DispatchQueue's synchronised call whenever audioPackets is involved. 
2. AudioParser's processNextDataPacket function can be called when throttler is nil. This only happens when SAPlayer is already up and running for one audio and I cleared SAPlayer to run for next. Further investigation shows that the issue is in AudioParser's initialiser where throttler is initialised after stream change listener. Consequently processNextDataPacket can be called in the listener before throttler is initialised.

Please see attached my current solution / modification in AudioParser and AudioParserPacketListener that seems to have resolved both above mentioned issues.
[Archive.zip](https://github.com/tanhakabir/SwiftAudioPlayer/files/6339482/Archive.zip)

**Comment by tanhakabir** [comment]
awesome! If it's easy to, it would be great if you could make a PR for your changes so that you get the full commit credit. If it's not easy then I can co-commit your changes!

**Comment by fayinsky** [comment]
Hi @tanhakabir , I'm using cocoapod so I'm not so sure how to make a PR from that. Feel free to double check what I did and co-commit the changes :) I'll do some research so that next time I can do it properly.

**Comment by tanhakabir** [comment]
@fayinsky to contribute to this library you would just need to fork and clone this repo and then copy and paste your changes and make a commit then PR from your fork. There's an example app in the repo as well to test your changes. 

But no worries if this is all too much! I'll review what you have tonight and co-commit if you don't get a chance to set up PRs on your end :)

**Comment by niczyja** [comment]
I've also experienced this crash frequently yesterday. Today I'm testing with @fayinsky fix applied and it didn't happen.
