### ISSUE TITLE
Audio duration is wrongly prettified to string

### ISSUE THREAD

**Issue by niczyja** [tanhakabir/SwiftAudioPlayer#95]
![IMG_0313](https://user-images.githubusercontent.com/5576359/115399202-3e9ea100-a1e8-11eb-9176-f4173b6fc5ad.jpg)

**Comment by tanhakabir** [comment]
Thanks! I notice you have a fix on your end, would you like to make a PR for your fix?

**Comment by niczyja** [comment]
Yes, I already made one: https://github.com/tanhakabir/SwiftAudioPlayer/pull/97
