### ISSUE TITLE
volume change has no effect

### ISSUE THREAD

**Issue by fayinsky** [tanhakabir/SwiftAudioPlayer#98]
Currently volume change is applied to AVAudioEngine's mainMixerNode and it seems to be not taking effect. Some stackoverflow posts suggest that mainMixerNode's volume control can only take effect after resetting engine itself.

A simple solution that appears to be working is replacing engine's mainMixerNode with player node.

```
public var volume: Float? {
    get {
        return player?.playerNode.volume
    }
    
    set {
        guard let value = newValue else { return }
        guard value >= 0.0 && value <= 1.0 else { return }
        
        player?.playerNode.volume = value
    }
}
```

**Comment by tanhakabir** [comment]
thank you! same as the other issue it would be awesome if you can PR so you get full credit!
